### ISSUE TITLE
silently drops batch calls

### ISSUE THREAD

**Issue by kumavis** [Level/abstract-leveldown#102]
If `db.batch` is called and there is no `_batch` specified it does nothing, and fails silently.

I'd expect it to either
* throw an error
* have a sane default that async.map's to `_put` and `_del`

Perhaps `batch`  guarantees being atomic. If we are unable to provide a sane default for that, then we should throw an error on a `batch` call

**Comment by ralphtheninja** [comment]
@kumavis Could you provide a snippet that reproduces this behavior? I'd be happy to take a look at it, unless you don't want to make a PR yourself :)

**Comment by vweevers** [comment]
It's not possible to have a sane fallback for `batch` (that would atomically commit).

> If we are unable to provide a sane default for that, then we should throw an error on a batch call

There's no precedent for that, many methods are noops for simplicity sake. If `_batch`  is not overridden an implementation won't pass the abstract test suite, so I don't see a benefit to *also* throwing from `_batch`.
