### ISSUE TITLE
Clean up test and testBuffer globals

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#126]
~~This is an investigative issue, will add points as I find them.~~

Get rid of `test` and `testBuffer` "globals", pass them on as function parameters instead

Try to get rid of `testBuffer` completely, if possible.

**Comment by ralphtheninja** [comment]
Fix https://github.com/Level/abstract-leveldown/issues/155 first.

**Comment by vweevers** [comment]
Ah I missed this. 👍

**Comment by ralphtheninja** [comment]
Ok, here's some code archeology.

I cloned the repos from https://github.com/level/awesome#stores

![downs](https://user-images.githubusercontent.com/308049/34084900-74e5bb44-e388-11e7-9a8e-efecfff20e24.png)

A search for `testBuffer` gave:

![testbuffer](https://user-images.githubusercontent.com/308049/34084957-4d6796e0-e389-11e7-90c1-de23e857fece.png)

It seems to me that all of them are passing in a plain `Buffer` object, although the content is different. Some pass in `new Buffer('somestring')` and some pass in data read from file.

The `testBuffer` variable is then used in two different tests:

* `.nonErrorKeys` where `testBuffer` is used as a _key_
* `.nonErrorValues` where `testBuffer` is used as a _value_

`testBuffer` doesn't seem to have anything to do with `BufferType`.

Conclusion:

Unless the actual content of `testBuffer` is important (doesn't seem likely) we could swap out `testBuffer` variable to a constant inside `abstract-leveldown`.

@vweevers Let me know what you think.

@juliangruber Any thoughts?

**Comment by ralphtheninja** [comment]
A few side notes:

* why is it important for implementations to be able to pass in `testFunc`? why not just use `tape`?
* ditto for the `testCommon` parameter, why not use `testCommon.js` inside `abstract-leveldown`?

**Comment by ralphtheninja** [comment]
Ideally the tests used in implementations should be (if possible)

```js
require('abstract-leveldown/abstract/put-get-del-test').all(whateverdown)
```

**Comment by vweevers** [comment]
> why is it important for implementations to be able to pass in testFunc? why not just use tape?

Because if they have additional custom tests, they must use the same `tape`. Otherwise, there'd be 2 test harnesses, executing tests at the same time.
