### ISSUE TITLE
What is the next callback structure?

### ISSUE THREAD

**Issue by MeirionHughes** [Level/abstract-leveldown#127]
The abstract down and iterator in here [doesn't seems to define](https://github.com/Level/abstract-leveldown#abstractiterator_nextcallback) what the callback for the iterator `next` should be. And the [implementation](https://github.com/Level/abstract-leveldown/blob/master/abstract-iterator.js#L24) implies the callback args could be anything. 

The only place where the structure for the next callback is _expected_ to be a certain way seems to be in the stream converter on levelup: https://github.com/Level/iterator-stream/blob/master/index.js#L25 which has it as: `function (err, key, value)` 

Can it be anything? or should it be `function (err, key, value, ...more)`?

cc: @ralphtheninja

**Comment by vweevers** [comment]
I don't know of any implementations using rest arguments (`...more`).

`function (err, key, value)` is correct, but some of our tests do rely on `!arguments.length` to check if the iterator has ended - rather than `key === undefined`. So this wouldn't work:

```js
return self._next(function (err, key, value) {
    self._nexting = false
    callback(err, key, value)
})
```

**Comment by MeirionHughes** [comment]
okay cool; I'm just making sure I can type the next as: 
```
  interface IteratorNextCallBack<TKey, TValue> {
    (err: any, key: TKey, value: TValue): void;
  }

  interface Iterator<TKey, TValue> {
    next(callback: IteratorNextCallBack<TKey, TValue>);
    end(callback: (err: any) => void): void;
  
    /** don't complain about untyped access */
    [index: string]: any;  
  }
```
