### ISSUE TITLE
range options should be serialized

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#130]
See https://github.com/Level/abstract-leveldown/issues/121#issuecomment-333484988.

@ralphtheninja @juliangruber should we include this in `levelup@2`? If so I can try to tackle this today/tomorrow.

**Comment by ralphtheninja** [comment]
Would be nice to know what happened here. Has this always been the case or did we break it?

**Comment by vweevers** [comment]
Has been the case since the `_serialize` functions were added. Simply forgot to include them in iterators.

**Comment by vweevers** [comment]
But no one has been bitten by this yet, it seems

**Comment by vweevers** [comment]
Even before `_serialize` (#85), when we just coerced non-buffers to strings, range options were not coerced AFAICT.

**Comment by vweevers** [comment]
@juliangruber can you think of any reason why this has been the case since forever? Are we missing something?

**Comment by juliangruber** [comment]
the null / undefined, buffer / utf8 etc situation was weird to me from the very beginning, and no one ever really understood the whole picture iirc

**Comment by juliangruber** [comment]
same as for example the `process.browser` checks

**Comment by ralphtheninja** [comment]
Maybe we could write some tests for it to to illustrate when it happens. What is the exact usage of the serialization code when doing `db.createReadStream()`? And when does it become a problem?

**Comment by vweevers** [comment]
So far I can't actually think of a use case that would fail without range option serialization. It merely *feels* like the right thing to do.

I know two Buffers can become equal when serialized to (UTF8) strings:

```js
Buffer('90', 'hex').toString() === Buffer('80', 'hex').toString()
```

Maybe we can find something there, some case where the sort order is off.

**Comment by vweevers** [comment]
Then again, if we need to actively search for issues..

**Comment by vweevers** [comment]
If nothing else, I think it's a safety mechanism. In normal use of `level(up)`, you'd use an *encoding* for non-standard types. Take:

```js
db.createReadStream({ gt: 12 })
```

The `db` here **_should_** be `level`, `levelup` with `encoding-down`, or otherwise backed by an `abstract-leveldown` that supports numbers for keys.

In case it is not, `abstract-leveldown` **_must_** serialize the `gt` option to a type supported by the underlying store. If not to prevent errors, then for symmetry with serialized keys.

For `leveldown` it'd be for symmetry, because the C++ currently ignores options that aren't buffers or strings. Without an encoding, the following example would output two keys (a stringified `1` and `2`) because the `gt` option is ignored, against expectation.

```js
db.batch([
  { key: 1, value: 'one' },
  { key: 2, value: 'two' }
], function (err) {
  db.createKeyStream({ gt: 2 }).on('data', function (key) {
    console.log(key)
  })
})
```

**Comment by vweevers** [comment]
> Even before _serialize (#85), when we just coerced non-buffers to strings, range options were not coerced AFAICT.

Makes sense because encodings used to be built-in, so users were protected against the above scenario (unless they used the `id` aka `none` encoding).

**Comment by vweevers** [comment]
@juliangruber @ralphtheninja in conclusion, I do think we need this, but it's not a priority. 🦆

**Comment by vweevers** [comment]
Found a use case. If `localstorage-down` wants to support Buffer keys, it needs to convert them to lexicographically ordered strings (with `d64` or `base64-lex`). Ideally `_serializeKey` is the only code path used to achieve this. Then internally, `localstorage-down` can just work on strings, and use native comparators for sorting keys.
