### ISSUE TITLE
Remove gaps from batch array?

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#138]
If you do `db.batch([null])`, or any other falsy value, should `abstract-leveldown` filter it?

I noticed that memdown has its own `!array[i]` check in `_batch()`, so I wondered if that's a job for `abstract-leveldown`. We currently do have a `typeof array[i] !== 'object'` check, which I didn't git blame yet, but this doesn't catch `null`.

@juliangruber @ralphtheninja

**Comment by juliangruber** [comment]
My first though was that for something a JSON backend `null` is an acceptable value, but then I saw that this is the completely wrong format too. It would have to be `db.batch([{ type: 'put', key: 'key', value: null }])`, so I agree we can filter those out, or even throw.

**Comment by ralphtheninja** [comment]
+1 for throwing + test
