### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by maxogden** [Level/abstract-leveldown#14]
I think it would be really useful to have a flag you could turn on when debugging that made leveldown write something like this to stdout:

```
OPEN "test"
PUT "ÿfooÿhello", "world", "String"
GET "ÿfooÿhello", "world", "String"
GET "ÿfooÿweeee", "Key not found in database [ÿfooÿweeee]", "NotFoundError"
```

I could monkeypatch to implement this today as a third party module but I wanted feedback on where in the stack something like this could go. I imagine that simple `if (verbose)` checks would get inlined by v8 etc

**Comment by vweevers** [comment]
Wrote https://github.com/vweevers/debugdown in 30 mins. Short of docs, usage is:

```js
var levelup = require('levelup')
var leveldown = require('leveldown')
var debugdown = require('debugdown')

var db = levelup(debugdown(leveldown('db')))

// Use db like you normally would
```

Here it is in action on the test suite of `leveldown` with `DEBUG=debugdown`:

![image](https://user-images.githubusercontent.com/3055345/42711245-6a8352e4-86e7-11e8-8f7e-cf864d172c07.png)
