### ISSUE TITLE
Go over callbacks and eliminate dezalgo

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#145]
See https://github.com/Level/abstract-leveldown/pull/142#issuecomment-346971549 as example

**Comment by vweevers** [comment]
I think I can tackle this - with a few `process.nextTick(cb, err)` - before a new major release.

@juliangruber any objections?

**Comment by juliangruber** [comment]
SGTM :)

**Comment by vweevers** [comment]
OK, I have some free time tomorrow. I hope to do this, #146, merge #142 and #144, release a major.

After that I can finish memdown v2, get it out in the wild, and then start on removing `process.browser` (which involves `abstract-leveldown`, `memdown` and `level.js`) - this will take some time and probably mean another major release.

**Comment by ralphtheninja** [comment]
> I think I can tackle this - with a few process.nextTick(cb, err) - before a new major release.
> 
> @juliangruber any objections?

Can we really do process.nextTick? Ideally we should use something that works in the browser and in node.

**Comment by vweevers** [comment]
nextTick arguments do work with browserify, I don't know about webpack.
