### ISSUE TITLE
Remove _isBuffer?

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#149]
Implementations no longer have a need to override `_isBuffer` in order to use typed arrays as buffers. Because with modern browserify, Buffer is a subclass of Uint8Array and conversions between the two are cheap. I.e. we can use Buffer (and `Buffer.isBuffer`) everywhere.

@ralphtheninja @juliangruber

**Comment by vweevers** [comment]
Tasks:

- [ ] `abstract-leveldown`: replace usage of `_isBuffer` with `Buffer.isBuffer`
- [ ] `abstract-leveldown`: remove `AbstractLevelDOWN.prototype._isBuffer`
- [ ] new release
- [ ] do the same for implementations (https://github.com/search?q=org%3ALevel+_isBuffer&type=Code)

**Comment by vweevers** [comment]
Maybe we can also remove `testBuffer` used in `put-get-del-test`?

https://github.com/Level/abstract-leveldown/blob/49a1bd7156f3c476eda8f67e0f79946ce3674f3e/abstract/put-get-del-test.js#L171-L172

I don't know the history of that one but assume it was also to enable use of replacement Buffer types.

@ralphtheninja

**Comment by ralphtheninja** [comment]
@vweevers Aye, I created an issue for it here https://github.com/Level/abstract-leveldown/issues/126 . Will look into it next.

**Comment by ralphtheninja** [comment]
@vweevers Should we remove `approximateSize` for version 4 as well?

**Comment by vweevers** [comment]
> Should we remove approximateSize for version 4 as well?

Sure why not :) Which other issues do you want to attack though? Note I didn't assign the ones I opened to the milestone you created.

**Comment by ralphtheninja** [comment]
@vweevers It depends on if we have more breaking changes coming. Adding tests and tweaking we should be able to release as minors. I just want to avoid ending up in a position where we implement for ages and never release :)

**Comment by ralphtheninja** [comment]
That said, it might also be worth it to spend time on releasing v4, since implementations rarely update `abstract-leveldown`. Trade offs :)

**Comment by vweevers** [comment]
Both true. I want to settle somewhere in between, in order to continue with `memdown`, my fork of `localstorage-down` and eventually `level-js`.

**Comment by vweevers** [comment]
@ralphtheninja I pushed my work to [webstorage-down](https://github.com/vweevers/webstorage-down) if you're interested.

**Comment by ralphtheninja** [comment]
> Both true. I want to settle somewhere in between, in order to continue with memdown, my fork of localstorage-down and eventually level-js.

Since you're actively developing on those *downs, lets have them drive the progress of `abstract-leveldown`. I'd like to remove `approximateSize` and then I'm happy with a new major.

**Comment by vweevers** [comment]
I have one failing browser test in `webstorage-down` that may need a `abstract-leveldown` change. Looking into it.

**Comment by vweevers** [comment]
→ #170
