### ISSUE TITLE
_setupIteratorOptions should also delete empty strings and null

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#154]
In addition to deleting empty Buffers:

https://github.com/Level/abstract-leveldown/blob/6edb4f8659e389e073ffb0a8d8c2dde694ec827a/abstract-leveldown.js#L216-L224

Because an empty Buffer, empty string and `null` should all behave the same way, at least according to the current tests. If we remove those options here, implementations don't need to worry about it.

**Comment by ralphtheninja** [comment]
I really don't like the `delete` thingie at all. I would prefer if this functionality could be lifted out into a function (it's not immediately clear to me what it does) which doesn't mutate the parameter. It should return a new object instead.

While writing it I realized `xtend()` here ensures that we aren't mutating the original `options` parameter so we're good, but it should be part of the function that xtends/mutates the original `options`.

**Comment by ralphtheninja** [comment]
Nevermind, what I just said above is exactly what the `._setupIteratorOptions` does already. :grinning:

**Comment by vweevers** [comment]
@ralphtheninja I think you're right though about:

> it should be part of the function that xtends/mutates the original options.

We could do:

```js
var hasOwnProperty = Object.prototype.hasOwnProperty;

AbstractLevelDOWN.prototype._setupIteratorOptions = function (options) { 
  var clean = {}

  for (var k in options) {
    if (!hasOwnProperty.call(options, k)) continue
    if (isRangeOption(k) && isEmptyRangeOption(options[k])) continue
    
    clean[k] = options[k]
  }

  return clean
}

function isRangeOption (k) {
  return (
    k === 'gt' || k === 'gte' ||
    k === 'lt' || k === 'lte' ||
    k === 'start' || k === 'end'
  )
}

function isEmptyRangeOption (v) {
  return v === '' || v == null || isEmptyBuffer(v)
}

function isEmptyBuffer (v) {
  return Buffer.isBuffer(v) && v.length === 0
}
```

**Comment by ralphtheninja** [comment]
> We could do:

I like it! Will update the PR.

**Comment by ralphtheninja** [comment]
Just realized I never made the PR, but my code pretty much looks like yours. Will push it up after https://github.com/Level/abstract-leveldown/pull/175
