### ISSUE TITLE
Export simple interface to entire abstract suite

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#157]
I'm working on a `localstorage-down` alternative (not because I need it, but was halfway done for PouchDB, and figured I see it through to get a new perspective on the whole buffer/browser/serialize story).

It cannot offer snapshot guarantees, which is fine if documented. But if you need to skip tests, like snapshots, you need to replace:

```js
require('abstract-leveldown/abstract/iterator-test').all(leveldown, test, testCommon)
```

With 5 lines more:

```js
require('abstract-leveldown/abstract/iterator-test').setUp(leveldown, test, testCommon);
require('abstract-leveldown/abstract/iterator-test').args(test);
require('abstract-leveldown/abstract/iterator-test').sequence(test);
require('abstract-leveldown/abstract/iterator-test').iterator(leveldown, test, testCommon, testCommon.collectEntries);
// require('abstract-leveldown/abstract/iterator-test').snapshot(leveldown, test, testCommon);
require('abstract-leveldown/abstract/iterator-test').tearDown(test, testCommon);
```

Or be clever about it:

```js
require('abstract-leveldown/abstract/iterator-test').snapshot = function() {}
require('abstract-leveldown/abstract/iterator-test').all(leveldown, test, testCommon)
```

Neither is ideal. Same story with other tests. In addition, some tests were missing from `localstorage-down`. No one would know.

So I was thinking: can we export a simple function from `abstract/index.js`, that runs all tests by default, takes the usual arguments, as well as options to exclude tests? Something like:

```js
require('abstract-leveldown/abstract')(leveldown, test, testCommon, {
  'open': {
    skip: 'openAdvanced'
  }
  'iterator': {
    skip: 'snapshot'
  },
  'approximate-size': {
    skip: 'all'
  }
})
```

Or move frequently skipped tests to separate files so we don't need nested options:

```js
require('abstract-leveldown/abstract')(leveldown, test, testCommon, {
  skip: [
    'open-advanced',
    'snapshot',
    'approximate-size'
  ]
})
```

Also makes it really easy to see what an implementation *doesn't* support.

@ralphtheninja @juliangruber

**Comment by ralphtheninja** [comment]
I like the idea, but would like to simplify (or improve) `test` and `testCommon` as well. E.g. something like (building on top of your idea):

```js
require('abstract-leveldown/abstract')(leveldown, {
  test: require('tap'), // optional, defaults to tape
  testCommon: testCommon, // required, needs to implement x methods
  tests: { // optional, defaults to all tests
    skip: [
      'open-advanced',
      'snapshot',
      'approximate-size'
    ]
  }
})
```
Additionally we could make sure that `testCommon` adheres to a specific api. I bet there are a lot of code duplication here, e.g. `location` and `lastLocation` which always use a counter (which could also be abstracted), `collectEntries` (always use `iterator.next()`?), `setUp` always use `cleanup`?

**Comment by ralphtheninja** [comment]
> Also makes it really easy to see what an implementation doesn't support.

:100:

**Comment by vweevers** [comment]
I was writing a comment, turned into a very long one full of rubber ducks 😄. I need to think on it.

**Comment by ralphtheninja** [comment]
:duck: :duck: :duck: :duck:

**Comment by ralphtheninja** [comment]
> I was writing a comment, turned into a very long one full of rubber ducks :smile:. I need to think on it.

I was just brain storming a bit. The current test setup feels a bit clunky to me, you need to know a lot of the internals and which tests to implement. I don't think most people know exactly what is needed and that usually results in copied code etc.
