### ISSUE TITLE
Move `collectEntries` to npm package

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#160]
We could publish it as something like `level-concat-iterator`. I see no reason for it to be included in `testCommon` or to be overridden, because it covers a very simple API that the iterator implementation must adhere to anyway.

@ralphtheninja

**Comment by ralphtheninja** [comment]
Lets do this.

**Comment by vweevers** [comment]
(the reason I suggested `level-concat-iterator` is to match the `concat-stream` name)

**Comment by ralphtheninja** [comment]
https://github.com/Level/concat-iterator
