### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#179]
And it would be nice to have a common approach for Level.

I see the changelog as an upgrade guide for humans. GitHub and git already provide the information in detail; summarizing that is the gap to fill. A commit list in the changelog is redundant, unless you're working offline. Still, online or offline, it often contains too much noise to answer the question "what changed *for me*"? 

One thing the commit list does provide is authorship, or maybe attribution is a better word. If people care about that (and it being available offline), we can opt to have both an upgrade guide and commit list.

I suggest:

- [x] No commit list (but keep old releases as-is)
- [ ] Describe breaking changes, with code examples where needed
- [x] For headers, use `<version> YYYY-MM-DD` for parsability
- [x] Include changelog in npm package (already true, here at least)
- [ ] On release, copy section to GitHub release

WDYT @ralphtheninja?

**Comment by vweevers** [comment]
Or, have both a `CHANGELOG.MD` and `UPGRADING.md`.

**Comment by ralphtheninja** [comment]
I was thinking about this yesterday and it's definitely something that has been lagging behind and we haven't really had any common practices as you say. Spot on! I like the idea of having code examples in the `CHANGELOG.md` file. Not sure we need another file `UPGRADING.md` on top of this though.

**Comment by vweevers** [comment]
> Not sure we need another file UPGRADING.md on top of this though.

Only matters if we want both a commit list and upgrade guide. Let's decide on that first

**Comment by ralphtheninja** [comment]
I want to remove the commit list, it's redundant as you pointed out.

**Comment by ralphtheninja** [comment]
@vweevers Should we keep the current `CHANGELOG.md` as it is? I.e. leave the commit list for previous versions but not adding any new for coming versions?

**Comment by vweevers** [comment]
I think yes. It's better than nothing

**Comment by ralphtheninja** [comment]
@vweevers It's a bit difficult to write something in the `CHANGELOG.md` for a future release, since you don't have the release date (it's in the future, duh). What's your view on what the workflow should look like for updating it?

**Comment by vweevers** [comment]
Add a header "5.0.0 - unreleased" and put new items under there.

**Comment by ralphtheninja** [comment]
And when you add new items you basically update that date later?

**Comment by vweevers** [comment]
We can (strive to) update the changelog whenever we make breaking changes or add features. Then on release, we merely have to replace "unreleased" with the date.

**Comment by vweevers** [comment]
Made me realize, I meant to write `<version> - YYYY-MM-DD` (with a dash).

**Comment by vweevers** [comment]
It's almost like the [Keep a Changelog](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md) convention. Might as well go all the way. So not "5.0.0 - unreleased" but simply "Unreleased".

**Comment by ralphtheninja** [comment]
Very nice changelog. Going to take that as inspiration. Hmm, would be nice with a tool for this as well.

**Comment by ralphtheninja** [comment]
@vweevers After thinking about it a bit, I think maybe we should have a `UPGRADING.md` after all. It feels a lot cleaner if `CHANGELOG.md` is just a changelog.
