### ISSUE TITLE
Canary system for most used dependents?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#184]
It would be nice to have some sort of canary system we can run to test effects in commonly used and important dependents based on `abstract-leveldown`.

This would help tremendously and avoid issues like https://github.com/level/abstract-leveldown/issues/71

**Comment by ralphtheninja** [comment]
Note: This could be a generic system that doesn't have anything to do with `abstract-leveldown`.

**Comment by ralphtheninja** [comment]
@nolanlawson Mentioned https://github.com/bahmutov/dont-break over here https://github.com/Level/abstract-leveldown/pull/85#issuecomment-246121318 where we broke `memdown` again.

**Comment by vweevers** [comment]
May also want to canary test [flumeview-level](https://github.com/flumedb/flumeview-level) and `encoding-down`, see https://github.com/Level/encoding-down/issues/42.
