### ISSUE TITLE
Remove unused testCommon parameter

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#192]
Signature:

https://github.com/Level/abstract-leveldown/blob/0d942fd45df5c9915269ded6f0f76fdfade11575/abstract/leveldown-test.js#L1

Call:

https://github.com/Level/abstract-leveldown/blob/0d942fd45df5c9915269ded6f0f76fdfade11575/test.js#L17

**Comment by vweevers** [comment]
(I'm not discovering these things, TypeScript is)

**Comment by ralphtheninja** [comment]
@vweevers Can we run this automatically somehow during tests?

**Comment by vweevers** [comment]
Yea, I'm working on running the full suite with `ts-node`.

**Comment by vweevers** [comment]
@ralphtheninja done in #195.
