### ISSUE TITLE
AbstractChainedBatch: pass options to _write

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#200]
Discovered in https://github.com/Level/abstract-leveldown/issues/193#issuecomment-359369932. If `_write` is defined, it does not receive the `options`, unlike `_batch`:

https://github.com/Level/abstract-leveldown/blob/0d942fd45df5c9915269ded6f0f76fdfade11575/abstract-chained-batch.js#L79-L83

Fixing this would be a breaking change. WDYT @ralphtheninja @juliangruber?

**Comment by juliangruber** [comment]
Would it be a breaking change, or rather a long outstanding bug fix? 🤔

**Comment by vweevers** [comment]
It's a breaking change per semver because implementations would have to change their function signature to `_write(options, callback)`.

**Comment by ralphtheninja** [comment]
Hmm I think I've seen an issue on this before, but can't remember where. `leveldown` would not be affected though:

https://github.com/Level/leveldown/blob/c7e2b762de1b99e97d8a86b8d6328da33cec3dc9/chained-batch.js#L26-L28

**Comment by vweevers** [comment]
@ralphtheninja hmm wait, if leveldown's signature is already `_write(options, callback)`.. why does that work?

**Comment by vweevers** [comment]
Ah, the C++ [takes the first argument as a callback](https://github.com/Level/leveldown/blob/c7e2b762de1b99e97d8a86b8d6328da33cec3dc9/src/batch.cc#L134-L135). So it would break leveldown.
