### ISSUE TITLE
TypeScript: asBuffer options should be defined here

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#201]
See https://github.com/Level/abstract-leveldown/pull/195#issuecomment-364105124. I realize the current typings are the way they are because of complicated generics. I'm opening this issue so that we don't forget and maybe fix it down the line.

@Level/typescript

**Comment by MeirionHughes** [comment]
done in https://github.com/Level/level-typings/blob/master/typings/abstract-leveldown.d.ts#L13
