### ISSUE TITLE
Auto casting to String on set??

### ISSUE THREAD

**Issue by davglass** [Level/abstract-leveldown#22]
I ran into this with my latest LevelDown abstraction:
https://github.com/rvagg/abstract-leveldown/blob/master/abstract-leveldown.js#L87

``` js
if (!this._isBuffer(value) && !process.browser)
    value = String(value)
```

Anyway we can make that an option and have `process.browser` default it to true? This way the abstraction can deal with the encoding?

My issue is that my backend server fully supports JSON encoding. Even if I said `encoding: 'json'` in my options, it's still casting that to a string on set. I'd like to have it just send the raw data to my abstraction and let me deal with the encoding.

If this is ok, I'll work on a PR just wanted to ask first :)

**Comment by vweevers** [comment]
> Anyway we can make that an option and have process.browser default it to true? This way the abstraction can deal with the encoding?

Since then, we added `_serializeKey` and `_serializeValue`, which indeed allows an implementation to choose *not* to stringify, or in fact do whatever it wants. Implementations like `memdown` and `level-js` use this serialization mechanism to allow storage of many JS types.
