### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#225]
Blocking https://github.com/Level/levelup/issues/568.

**Comment by vweevers** [comment]
Also need a new memdown

**Comment by ralphtheninja** [comment]
@vweevers I'll update leveldown/rocksdb with the latest abstract-leveldown after that. Since we have removed node 4 only, we can just do that with a patch.

**Comment by ralphtheninja** [comment]
@vweevers Want to take this or should I do it?

**Comment by vweevers** [comment]
Go ahead. I was just opening issues, not putting in any real time yet
