### ISSUE TITLE
Consider a factory pattern in test suite

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#227]
Where `testCommon.factory()` would return a fresh `db`. This allows implementations to add options to their constructor, if they need to. See https://github.com/andrewosh/hyperdown/issues/2 for background.

@andrewosh @ralphtheninja @juliangruber

**Comment by vweevers** [comment]
@andrewosh here's another example of constructor options: https://github.com/Level/level-js. With `levelup`, it can be used like so:

```js
var db = levelup(leveljs('my-db', { prefix: 'my-app-' }))
```

IMO this is much cleaner than `open` options, which would have to be passed through `levelup`. It wouldn't be immediately apparent that the `prefix` option belongs to `level-js`:

```js
var db = levelup(leveljs('my-db'), { prefix: 'my-app-' })
```

@ralphtheninja maybe we should start following the constructor pattern everywhere, including `leveldown`.

**Comment by ralphtheninja** [comment]
> @ralphtheninja maybe we should start following the constructor pattern everywhere, including leveldown.

:+1:

**Comment by vweevers** [comment]
Not yet, there are a lot of angles to consider (and we're currently working on other stuff).

As a temporary solution, you might be able to pass a wrapper to the abstract tests. Along the lines of

```js
require('abstract-leveldown/abstract/get-test').all(wrapper, test)

function wrapper (location) {
  hyperdown.call(this, location, {
    reduce: (a, b) => {
      if (!a) return b
      return a
    }
  }
}

util.inherits(wrapper, hyperdown)
```

**Comment by andrewosh** [comment]
Thanks a bunch! I'll give that a shot
