### ISSUE TITLE
Add Symbol.asyncIterator to iterator

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#235]
Background and use cases in Level/levelup#477 and Level/levelup#491.

**Comment by MeirionHughes** [comment]
I've added an alternative take on this. https://github.com/Level/abstract-leveldown/tree/feature/async-iterator in theory it will just not do anything on older node, but can still be parsed as it manually making the async iterator object.

**Comment by vweevers** [comment]
IMO that much boilerplate code is just not worth it and a sign that async iterators hadn't matured yet. Async generators make it so much cleaner and digestible, similar to what `async/await` does for promises.

**Comment by MeirionHughes** [comment]
true; yes - generators are nice, but there is (or at least was) a major short coming with the generator approach if you absolutely need to clean-up: [you don't know if the user breaks out or not.](https://stackoverflow.com/questions/46414415/how-can-i-find-out-if-a-javascript-iterator-terminates-early). 

i.e. 

```
async function *(){
  yield 1; 
  yield 2; 
  yield 3;
}

for await (let item of source()){
   break;
}
```

My solution (and answer to the SO) [is was to hack the `return`](https://www.npmjs.com/package/@async-generators/terminator), which is even more boiler plate than simply rolling your own `{next, return, error}` object.

**Comment by MeirionHughes** [comment]
I actually gave up on using async iterators last year - I've gone to rxjs for everything at work now. Its just more consistent as you absolutely know when something unsubscribes.

**Comment by MeirionHughes** [comment]
You absolutely want to use a generator you could maybe do it like this: 
```js
AbstractIterator.prototype[Symbol.asyncIterator] = function(){
    let it = (async function * generate() {
      try {
        var kv
    
        while ((kv = await this.next()) !== undefined) {
          yield kv
        }
      } finally {
        await this.end()
      }
    })().bind(this);

    it.return = async function(){
      await this.end();
    }.bind(this)
    
    return it;
  } 

```

**Comment by vweevers** [comment]
> there is (or at least was) a major short coming with the generator approach if you absolutely need to clean-up: you don't know if the user breaks out or not..

That's terrible. Good to know, thanks
