### ISSUE TITLE
Don't use __dirname in testCommon

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#240]
https://github.com/Level/abstract-leveldown/blob/d806bf147d12186990db7fdc6da4c95e7a558ccc/testCommon.js#L8

Should probably use `process.cwd()`, or better yet, a unique temporary directory.

Ref https://github.com/Level/leveldown-hyper/pull/68#discussion_r196815629

**Comment by ralphtheninja** [comment]
I'm wondering about `testCommon.js` in general. It has some `process.browser` checks to avoid requiring `fs` and `rimraf`, which I guess has to do with being able to run it in the browser.

@vweevers WDYT about removing the `process.browser` checks completely from this file? They don't really make sense to me, other than preventing errors. Implementations for the browser like `level-js` do provide their own `testCommon` anyway.

**Comment by ralphtheninja** [comment]
Oh, right. Maybe implementations do use parts of `testCommon.js`, e.g. `collectEntries`. Forgot about that.

**Comment by ralphtheninja** [comment]
An advantage with using `__dirname` or `process.cwd()` is that they are existing folders and we don't need to clean them up. If we use unique and random folders they will not be cleaned up as it is right now.

**Comment by vweevers** [comment]
If we add new node-only dependencies (like `tempy`) before moving out reused parts like `collectEntries`, then each browser-based implementation must also add a browserify exclusion for that dependency. Unless we do that here (by wrapping `tempy` in a local module).

I'm all for using `tempy` (without cleanup, and calling it for each `location()` so we don't need `dbidx`), but prefer to first make `testCommon` completely node-only. Which I *think* only means moving out `collectEntries`.

**Comment by ralphtheninja** [comment]
A trade off would be to do `process.cwd()` as you mentioned and not care about `tempy` at all.

**Comment by ralphtheninja** [comment]
> I'm all for using tempy (without cleanup, and calling it for each location() so we don't need dbidx), but prefer to first make testCommon completely node-only. Which I think only means moving out collectEntries.

:+1: 

`collect-iterator-entries` could also be a separate module

**Comment by vweevers** [comment]
> collect-iterator-entries could also be a separate module

We have an old issue for that :)

**Comment by vweevers** [comment]
=> https://github.com/Level/abstract-leveldown/issues/160

**Comment by ralphtheninja** [comment]
`collect-iterator-entries` could also check which context it's running in, and do `process.nextTick()` if present and fallback to `setTimeout()`.

**Comment by ralphtheninja** [comment]
Or maybe just use `immediate` module.

**Comment by vweevers** [comment]
> collect-iterator-entries could also check which context it's running in, and do process.nextTick() if present and fallback to setTimeout().

I prefer that being passed in.

**Comment by vweevers** [comment]
I had a look at memdown; it currently doesn't have its own `testCommon`: https://github.com/Level/memdown/blob/760b3755b9d0d7f5b58c02febc17243a86b3ed15/test.js#L2

But when we have a `level-concat-iterator` or `collect-iterator-entries` module, it'll be easy to write memdown's own `testCommon`.

**Comment by vweevers** [comment]
`setup` and `teardown` can be noops in memdown.

**Comment by vweevers** [comment]
Afterwards we can also remove:

https://github.com/Level/abstract-leveldown/blob/a36c04fe5c21e568291f49e2235a9b4cdfde2292/package.json#L26-L28

**Comment by ralphtheninja** [comment]
Unassigned myself for now and closed incorrect PR.

**Comment by vweevers** [comment]
@ralphtheninja do you remember why we need `nextTick` at all in concat-iterator?

**Comment by ralphtheninja** [comment]
> @ralphtheninja do you remember why we need nextTick at all in concat-iterator?

That's a really good question. I don't see any immediate use of it. It seems to originate from `leveldown` https://github.com/Level/leveldown/commit/265bed5 and it basically looks the same

**Comment by ralphtheninja** [comment]
The reason we need it now is to replace `process.nextTick` with e.g. a function that wraps `setTimeout`, but why do we need it at all? It seems to me that it should be enough to just call `next()` directly?
