### ISSUE TITLE
Make db argument of iterator and chained batch required

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#255]
So that iterators and chained batches will always have a `db` property (or `_db`, normalizing that is a second question). This prevents garbage collection of `db`.

https://github.com/Level/abstract-leveldown/blob/7b079c5510f0ae354ae9503849ac7d9a0aa01551/abstract-iterator.js#L1-L2

https://github.com/Level/abstract-leveldown/blob/7b079c5510f0ae354ae9503849ac7d9a0aa01551/abstract-chained-batch.js#L1-L2

---

- [x] iterator
  - [x] make it required
  - [x] rename to `.db` (already the case)
  - [x] document
- [x] chained batch:
  - [x] make it required (#257)
  - [x] rename to `.db`
  - [x] document

**Comment by vweevers** [comment]
In addition, if `_db` is guaranteed to be there, we no longer need these "proxy" methods:

https://github.com/Level/abstract-leveldown/blob/7b079c5510f0ae354ae9503849ac7d9a0aa01551/abstract-chained-batch.js#L7-L13

**Comment by vweevers** [comment]
Should it be `iterator.db` (public) or `iterator._db`?

**Comment by ralphtheninja** [comment]
> Should it be iterator.db (public) or iterator._db?

I have no strong opinion. If public it should be documented I guess.

**Comment by vweevers** [comment]
Let's go with public + docs. No particular reason.
