### ISSUE TITLE
Update upgrade guide

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#262]
We need to rewrite the upgrade guide for the currently unreleased functionality, since `test/common` is now both for node and the browser (empty `setUp()` and `tearDown()`).

- [x] Implementations need to create their own `factory` and pass in `testCommon`
- [x] ~~`testCommon` parameter no longer has default value (NYI)~~
- [x] `seek`
- [x] ~~`test/common` is a function (NYI)~~
- [x] ~~removed deprecated `module.exports.snapshot` test (NYI)~~
- [x] ~~removed empty `errorValues` test (NYI)~~
- [x] Refactored chained batch (pending #257)
- [x] Removed `testCommon.collectEntries`
- [x] ~~`test/close-test.js` updated with `setUp` and `tearDown` (https://github.com/Level/abstract-leveldown/pull/279)~~
- [x] Serialization (pending #277)
- [x] Remove "Empty errorValues() test was removed"

See discussion in #258

**Comment by ralphtheninja** [comment]
So some of these are no longer relevant, given that `test/common` will be removed.

**Comment by ralphtheninja** [comment]
Same for `errorValues` test. Only `seek` stuff left for now.

**Comment by vweevers** [comment]
Ticked off the rest of the boxes to see what's done. Added chained batch.

**Comment by ralphtheninja** [comment]
Added note on `test/close-test.js`

**Comment by vweevers** [comment]
That's another internal detail, no?

**Comment by ralphtheninja** [comment]
> That's another internal detail, no?

True. I was just thinking that some implementations are currently calling `.close()`. Maybe explaining about a single test function is enough?

**Comment by vweevers** [comment]
All implementations should no longer `require()` the individual tests, so we don't have to explain changes we make to those internals :)

**Comment by vweevers** [comment]
Added: Remove "Empty errorValues() test was removed" ;)
