### ISSUE TITLE
Add seek tests

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#269]
- [x] Import tests from `leveldown/test/iterator-test.js` (in `next` branch)
  - [x] ~~[iterator#seek throws if target is empty](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L6)~~ The empty-check is currently performed by `leveldown`
  - [x] [iterator is seekable](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L30)
    - [x] rename to `iterator#seek() to string target`
  - [x] [iterator is seekable with buffer](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L46)
     - [x] rename to `iterator#seek() to buffer target`
     - [x] skip if `testCommon.bufferKeys` is false
  - [x] [reverse seek in the middle](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L62)
    - [x] rename to `iterator#seek() on reverse iterator`
  - [x] [iterator invalid seek](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L73)
    - [x] rename to `iterator#seek() to out of range target`
  - [x] [reverse seek from invalid range](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L84)
    - [x] rename to `iterator#seek() on reverse iterator to out of range target`
  - [x] ~~[iterator optimized for seek](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L95)~~ (hooks into `iterator.cache` which is a `leveldown` detail)
  - [x] [iterator seek before next has completed](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L133)
     - [x] rename to `iterator#seek() throws if next() has not completed`
  - [x] ~~[close db with open iterator](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L151)~~ (unrelated)
  - [x] [iterator seek after end](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L169)
    - [x] rename to `iterator#seek() throws after end()`
  - [x] [iterator seek respects range](https://github.com/Level/leveldown/blob/1fd0bdb9b43b94fa26a4593716746ee22b3f496e/test/iterator-test.js#L189)
    - [x] rename to `iterator#seek() respects range`
- [x] Add additional tests
  - [x] ~~`target` is serialized~~ ([done](https://github.com/Level/abstract-leveldown/blob/a8aa1c27c37d409adbca9fbe2fd1582a1d380e3f/test/self.js#L692))
- [x] ~~Test that implementation doesn't define public `seek`, which is currently the case in `leveldown` and friends. They should define `_seek` instead.~~ This would require `Object.getPrototypeOf` shenanigans, making assumptions about the implementation and its prototype chain.

**Comment by vweevers** [comment]
Added a list of tests, so we can easily see which ones can be removed from leveldown later.

**Comment by vweevers** [comment]
List is outdated, should update after https://github.com/Level/leveldown/pull/506.

**Comment by ralphtheninja** [comment]
@vweevers Nice that you're hacking a bit on level. I have been doing other stuff for a while. Will try to get back into level shortly.

**Comment by vweevers** [comment]
List updated.
