### ISSUE TITLE
Fix propertly typos

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#281]
https://github.com/Level/abstract-leveldown/blob/ffba12f714f543145dede972f8ae9fa937eb5dc6/test/del-test.js#L64

https://github.com/Level/abstract-leveldown/blob/ffba12f714f543145dede972f8ae9fa937eb5dc6/test/put-get-del-test.js#L75

**Comment by ralphtheninja** [comment]
https://github.com/Level/abstract-leveldown/commit/ae8d41b6f2ac7835caf6a4f9ca77a97c2e2bf823
