### ISSUE TITLE
Add bufferKeys test suite option

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#287]
To replace `process.browser` checks in e.g.:

https://github.com/Level/abstract-leveldown/blob/48484ce12e8e59c0665b50b4bc085809bd662cf4/test/put-get-del-test.js#L124-L127

**Comment by vweevers** [comment]
If we wait with this, it'd be another major, but on the other hand, v6 is already quite big.

**Comment by ralphtheninja** [comment]
Chuck it in!

**Comment by ralphtheninja** [comment]
I could start working on the CHANGELOG on a separate branch.
