### ISSUE TITLE
open, close, and open

### ISSUE THREAD

**Issue by calvinmetcalf** [Level/abstract-leveldown#30]
I don't believe there is a test that opens a db, closes it and then opens it again, came up for me with sqldown

**Comment by timkuijsten** [comment]
This issue can be closed: https://github.com/Level/abstract-leveldown/blob/master/abstract/open-test.js#L51-L67

**Comment by ralphtheninja** [comment]
> This issue can be closed: https://github.com/Level/abstract-leveldown/blob/master/abstract/open-test.js#L51-L67

:+1:
