### ISSUE TITLE
How to import test suite?

### ISSUE THREAD

**Issue by gradorsys** [Level/abstract-leveldown#304]
I do not get it.
I am writing an encryption for leveldown

I use abstract-leveldown 5.0.0
```
npm install -D abstract-leveldown@5.0.0
```
The Documentation says to 

```js
const suite = require('abstract-leveldown/test') 
// suite === {}`
```

But then suite is empty object 
When i look in my "nodemodules/abstract-leveldown" folder there are no tests.
Were they forgotten to publish them in the package?
Was it done on purpose?
What is the correct way to require them so that I do not need to copy all the files myself?

**Comment by vweevers** [comment]
Sorry about that! We've been refactoring the test suite - and updated documentation in the `master` branch accordingly - but this is not yet published. And sadly, the current version (5.0.0) has no documentation on how to call the test suite. You can have a look at [memdown's test suite](https://github.com/Level/memdown/blob/64a5a910d82379cd21947805b6d850fa3a64eb04/test.js#L13-L30) and/or other implementations.

> I am writing an encryption for leveldown

That sounds like an awesome project!

**Comment by vweevers** [comment]
> npm install -D abstract-leveldown@5.0.0

Side note: `abstract-leveldown` is a runtime dependency, so you'll most likely want to save it to `dependencies` rather than `devDependencies`.

**Comment by gradorsys** [comment]
Thx a lot. The information was of great help.
I will let you know when it is ready for feedback.
