### ISSUE TITLE
using empty location + open causes weird results

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#59]
If I do the following:

```js
var leveldown = require('leveldown')
var db = leveldown('')
db.open(console.log.bind(console))
```

I get the following output:

```
[Error: IO error: /LOCK: Permission denied]
```

Which is kind of odd. I propose that we make `AbstractLevelDOWN` throw an error if a zero length string is given, instead of finding out in `open()` that we couldn't open that location. We already know it will fail and might as well error in the constructor.

**Comment by juliangruber** [comment]
Agreed. `.` and even `/` should be valid locations, but not the empty string. `if (!location) ...` should be fine
