### ISSUE TITLE
Breaking change in v2.2.1

### ISSUE THREAD

**Issue by willwhite** [Level/abstract-leveldown#61]
The recent 2.2.1 patch release includes [a breaking change](https://github.com/Level/abstract-leveldown/compare/3bdc39eb11a5342eff41936297574a57d55aa298...261589abb20c9965d45a98af1b73e8d0cd4a8b18#diff-a5b095a3840cc9a19a7b58565f942640R11) around validation of the location argument. This change is breaking downstream users of this project including https://github.com/mhart/dynalite.

[semver](http://semver.org/) reserves minor and patch level increments for backwards-compatible changes only. Any chance v2.2.1 can be unpublished and rerolled as a major v3.0.0 release?

**Comment by juliangruber** [comment]
can you explain why this is a breaking change? it was never documented what an empty string `""` as location would do and so this is a fix as it prevents unexpected behavior.

**Comment by juliangruber** [comment]
ah i guess if location doesn't matter, like when using memdown, people like to pass an empty string?

**Comment by juliangruber** [comment]
memdown does that for example: https://github.com/Level/memdown/blob/master/memdown.js#L124

**Comment by juliangruber** [comment]
i reverted and published 2.2.2, sorry for the trouble. i'm opening a new issue for a better strategy.

**Comment by willwhite** [comment]
Thanks!
