### ISSUE TITLE
Decide whether gte/gt/lte/lt should take precedence over start/end or ..?

### ISSUE THREAD

**Issue by rvagg** [Level/abstract-leveldown#70]
See https://github.com/dominictarr/ltgt/issues/1 for details

Basically there exists a discrepancy between memdown and leveldown where memdown will decide to prefer `lte` and `lt`, discarding `end` if it exists, while leveldown takes the minim of the options. Same would go for `gte`, `gt` and `start` (and the `reverse` combinations as well).

One of them should be wrong, we need to decide which and implement conformance tests for it here.

**Comment by mcollina** [comment]
That's a fine detail. I would go for `lt` over `end`, and `gt` over `start`. I would also deprecate `start` and `end`.

**Comment by juliangruber** [comment]
I'm as well for giving the more specific and easy to grasp options, `gte/gt/lte/lt`, precedence over `start/end`.

**Comment by dominictarr** [comment]
my position is not use `start/end` if the relavant `gt/lt/gte/lte/reverse` option is defined.
(start may indicate the high value (`lt`) if it's `reverse=true`

**Comment by vweevers** [comment]
Closing because of https://github.com/Level/community/issues/86.
