### ISSUE TITLE
ES6 is ending up in the browserify builds

### ISSUE THREAD

**Issue by nolanlawson** [Level/abstract-leveldown#71]
The `const` keyword is ending up the browserify builds for memdown (e.g. see https://wzrd.in/standalone/memdown@latest), and it is breaking various browsers, notably in the Hoodie tests (Hoodie uses PouchDB uses MemDOWN uses AbstractLevelDOWN). https://github.com/pouchdb/pouchdb/issues/4215

I'm not sure what the most elegant way to fix this is, but for the time being I would suggest just removing `const` from the source, or else making it a build step to only output ES5-compatible Node code.

**Comment by juliangruber** [comment]
closing for now since your pull request landed, if anyone makes a good point we could say use a transpiler and add back the `const`

**Comment by ralphtheninja** [comment]
@nolanlawson Would this still be an issue today?

**Comment by ralphtheninja** [comment]
cc @vweevers Would be nice with canaries for issues like this.

**Comment by vweevers** [comment]
Note memdown's test matrix would have to include more browser versions, for it to catch this. Luckily the sauce labs setup is stable now, so we have some room to add back old versions.
