### ISSUE TITLE
ranges-test.js is not being run by `npm test`

### ISSUE THREAD

**Issue by nolanlawson** [Level/abstract-leveldown#73]
I wanted to add some tests for cases where `lte` is less than `gte` (see https://github.com/maxogden/level.js/pull/45 for background), but it looks like `ranges-test.js` isn't even being run anywhere? Is there a reason it's disabled?

**Comment by juliangruber** [comment]
not that i'd know of...

**Comment by vweevers** [comment]
This file was almost entirely redundant and hence removed in #161. See also #152 for @ralphtheninja's detailed analysis. TLDR: we now have `iterator-test.js` to test the basic API and `iterator-range-test.js` for ranges.
