### ISSUE TITLE
_checkKey prevents saving of empty values

### ISSUE THREAD

**Issue by okv** [Level/abstract-leveldown#74]
Hi, there.
According to this https://github.com/Level/levelup/issues/223 empty string is valid value but currently [_checkKey](https://github.com/Level/abstract-leveldown/blob/1259fc4b0ab6d7e54c9936d990ea5447d780112d/abstract-leveldown.js#L269) returns an error. So memdown and other down's still don't pass empty string.

**Comment by dcousens** [comment]
You can save an empty (zero-length) `Buffer` without issue.

**Comment by vweevers** [comment]
This is no longer an issue in `abstract-leveldown`.
