### ISSUE TITLE
detecting approximateSize presence

### ISSUE THREAD

**Issue by mcollina** [Level/abstract-leveldown#8]
`approximateSize` support is not widespread: MemDOWN and Level.js do not have it.

However, this interface do not provide a way for knowing if that support is there or not.

We need it for https://github.com/mcollina/node-levelgraph/pull/23.

**Comment by vweevers** [comment]
Ref https://github.com/Level/deferred-leveldown/issues/35.

**Comment by vweevers** [comment]
Absorbing into https://github.com/Level/community/issues/83.
