### ISSUE TITLE
calling the last callback passed to next multiple times

### ISSUE THREAD

**Issue by timkuijsten** [Level/abstract-leveldown#82]
While implementing native IndexedDB support for Level.js I found that the current implementation might call the last callback that is passed to next() multiple times, instead of exactly once, what I assumed.

I've created a test that checks for this and demonstrates the problem in level.js: https://github.com/timkuijsten/level.js/commit/b27db4b58e1f09d2bbf9c0d173f899e3a6b83d12

I've raised this question in https://github.com/maxogden/level.js/pull/51#issuecomment-182506309 as well.

**Comment by vweevers** [comment]
This sounds like a problem in the implementation (which calls the callback), not `abstract-leveldown`. Besides that, `level-js` has since seen a major upgrade.
