### ISSUE TITLE
I would like to develop a new *down. Where do I start?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/abstract-leveldown#91]
How do you use this package to verify that an arbitrary *down is leveldown compatilble?

**Comment by juliangruber** [comment]
check out how others do it :) for example:

https://github.com/Level/leveldown/blob/master/test/close-test.js

or

https://github.com/maxogden/level.js/blob/master/test/test.js

**Comment by No9** [comment]
Agree with @juliangruber 
You might also want to take a *down implementation that closely reflects the underlying persistence mechanism. i.e. mydown if you looking to support an SQL type backend etc
Anyhoo there is a full list here 
https://www.npmjs.com/browse/depended/abstract-leveldown

**Comment by fergiemcdowall** [comment]
@juliangruber cheers! Will do.

@No9 I wasnt aware of the https://www.npmjs.com/browse/depended/ endpoint- thats a very useful way of finding all the *downs
