### ISSUE TITLE
Put implementation converts `null` to `"null"` not `""`.

### ISSUE THREAD

**Issue by bigeasy** [Level/abstract-leveldown#98]
There are new tests that assert that when a `null` or `undefined` value is put into the database that it will be retrieved as an empty string. I assume this means it should be converted to an empty string before insertion. The `_serializeValue` method converts using `String(value)` which converts `null` to `"null"` and `undefined` to `"undefined"`.

**Comment by ralphtheninja** [comment]
See https://github.com/Level/abstract-leveldown/pull/119
